# This is a basic workflow to help you get started with Actions

name: Test Deploy

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Add Known Hosts 
        run: |
          mkdir -pv ~/.ssh
          echo "${{ secrets.KNOWN }}" > ~/.ssh/known_hosts
      
      - name: Add SSH key
        run: |
          touch ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "${{ secrets.KEY }}" > ~/.ssh/key

      - name: Test file on the remote server
        run: ssh -i ~/.ssh/key "${{ secrets.SSH }}" echo "hello" > testFile
        
      - name: Test Deploy on the remote server
        run: ssh -i ~/.ssh/key "${{ secrets.SSH }}" 'cd ~/website/ && git pull --force --no-rebase && npm install && npm run start && rm -r /var/www/html/*; cp -r ~/website/public/* /var/www/html/'

      - name: Test echo locally
        run: |
          echo The worker finished
      #- uses: mdelillo/ssh-server-action@v1
      #  with:
      #    ngrok-authtoken: ${{ secrets.NGROK }}
      #    ssh-public-key: ${{ secrets.PUBLICNGROK }}
