name: Test Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Create SSH config folder
        run: mkdir -pv ~/.ssh

      - name: Add Known Hosts
        run: |
          echo "${{ secrets.KNOWN }}" > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
      
      - name: Add SSH key
        run: |
          touch ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "${{ secrets.KEY }}" > ~/.ssh/key

      - name: Deploy on the remote server
        # -q is required to remove IP leakage when warning about adding the SSH host key that is already kwnown
        run: ssh -q -i ~/.ssh/key "${{ secrets.SSH }}" 'cd ~/website/ && git pull --force --no-rebase && npm install && npm run start && rm -r /var/www/html/*; cp -r ~/website/public/* /var/www/html/'

      #- uses: mdelillo/ssh-server-action@v1
      #  with:
      #    ngrok-authtoken: ${{ secrets.NGROK }}
      #    ssh-public-key: ${{ secrets.PUBLICNGROK }}
